### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by julien-arch** [XHUJOY/CycleGAN-tensorflow#1]
Great that this is on TensorFlow! I was wondering if it'd be possible to have multi-GPU support?

**Comment by petergerten** [comment]
I am also curious about this. Not sure why this issue was closed without any comment.
I tried
`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 python main.py `
but only GPU 0 was used.

**Comment by xhujoy** [comment]
This repo doesn't support multi-GPU, so only one GPU can be used. It is stable and I don't consider to add any new feature now. You may need to write the code by yourself for multi-GPU.

**Comment by petergerten** [comment]
Thanks for the clarification :)

**Comment by advance512** [comment]
@xhujoy 
Any pointer on how to do this?
Data parallelism? Where would you split the execution, use multi-towers?
