### ISSUE TITLE
Results Good?

### ISSUE THREAD

**Issue by zizhaozhang** [XHUJOY/CycleGAN-tensorflow#10]
Hi
Thanks for sharing your code!
Have you tested the results and compared with the original version?

**Comment by XHUJOY** [comment]
Sry, i also don't know why this project can't archive the result of original version.

**Comment by zizhaozhang** [comment]
Yeah. I trained and found the results not reasonable. Probably there is a bug on model construction.

**Comment by Hatuw** [comment]
Maybe. But I can't found the bug on model construction.

**Comment by zizhaozhang** [comment]
I found another [implementation](https://github.com/architrathore/CycleGAN). Maybe you want to take a look . It seems it showed good results.

**Comment by XHUJOY** [comment]
thx for your help

**Comment by iairose** [comment]
Help!
----------------------------------
python main.py --dataset_dir=horse2zebra
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from model import cyclegan
  File "/notebooks/CycleGAN-tensorflow/model.py", line 10, in <module>
    from module import *
  File "/notebooks/CycleGAN-tensorflow/module.py", line 3, in <module>
    from ops import *
  File "/notebooks/CycleGAN-tensorflow/ops.py", line 4, in <module>
    import tensorflow.contrib.slim as slim
ImportError: No module named slim

**Comment by Hatuw** [comment]
You can check your tensorflow and install the latest version of TF-slim. By the way, you should create a new issue for another problem. @iairose

**Comment by Youngjung** [comment]
This may help.
https://github.com/LynnHo/CycleGAN-Tensorflow-Simple

**Comment by XHUJOY** [comment]
This problem has been solved and we got results similar to [original results](https://junyanz.github.io/CycleGAN/). There are some details:

- Remove the last norm layer of G net
- Joint training two G nets
- Change `--ngf 32` to `--ngf 64`
- Use the learning rate schedule same with the original paper
