### ISSUE TITLE
Excuese me , is there any Caffe code?

### ISSUE THREAD

**Issue by LouiValley** [XHUJOY/CycleGAN-tensorflow#12]
Is there any code about CycleGan that can run in Caffe? Cause there is only code can run in tensorflow. :）
what is more, when I run your code, there is no loss print,  will it be reasonable to print ga2b_loss  & gb2a_loss?

**Comment by XHUJOY** [comment]
I don't know any code with caffe.
Implementing cyclegan with caffe  is not easy i think.
