### ISSUE TITLE
Parameters not used

### ISSUE THREAD

**Issue by Franziska-Mueller** [XHUJOY/CycleGAN-tensorflow#13]
The main.py script offers some parameters that one can change, e.g. enable/disable flipping, image size etc. Some of these parameters (at least the ones mentioned before) are not passed to the actual image loading functions.
- model.py, line 147: load_data is called without flip parameter so even if you pass "--flip=0" to the script, it will still flip the images for training (since default is True)
- model.py, line 254: load_test_data is called without image size parameter and hence will always be the default size
- utils.py, line 48: preprocess_A_and_B is called without parameters for load_size and fine_size, they are always set to the default values

**Comment by XHUJOY** [comment]
The code has been cleaned and these issues has been solved, thx.
