### ISSUE TITLE
Load Failed

### ISSUE THREAD

**Issue by AkhilSinghRana** [XHUJOY/CycleGAN-tensorflow#14]
When I try to run the script main.py for horse2zebra dataset which was downloaded as told in readme, I get a error saying Load Failed, once the graph is built. no further Information is given as why this is happening. Is there a bug in the script or some dependencies which are missing. 
I am using tensorflow 1.3 gpu version

**Comment by XHUJOY** [comment]
Hi, I think you should extract the rar file to` ./checkpoint/` not` ./checkpoints/`. It' s a typo in README.txt.

**Comment by AkhilSinghRana** [comment]
Hi @XHUJOY  Thanks for the quick response. I am using 'bash ./download_dataset.sh horse2zebra', to download the dataset which creates a new directory inside ./datasets. Is it not how it should be done ? While training I just give this directory as an argument.

**Comment by XHUJOY** [comment]
you can use soft link,
`ln -s /your/dataset/path ./datasets`

**Comment by shirishr** [comment]
@xhujoy
I am a newbie with ubuntu....I am on ubuntu 16.04, python 3.6 tensorflow 1.6

In the Tereminal I see output
discriminatorA/d_bn3/offset:0
discriminatorA/d_h3_pred/Conv/weights:0
Illegal instruction (core dumped)

Any suggestions?
