### ISSUE TITLE
Load Failed

### ISSUE THREAD

**Issue by niccanicci** [xhujoy/CycleGAN-tensorflow#16]
![se](https://user-images.githubusercontent.com/32840015/31655320-17694aba-b35b-11e7-94eb-4ff9216a81de.png)
@xhujoy 
Hello @xhujoy , im a newbie but here i encountered some problem during running this model,im not sure how to fix it. i got an load failed error message and the epoch seems to be running even the load failed. Thank you if you can get me out of this problem...

**Comment by xhujoy** [comment]
hi, @niccanicci 

The program is OK and you can ignore the error message. The message is meaningful when `args.continue_train` is true. I have fixed this bug already, thanks.

**Comment by niccanicci** [comment]
Thank you @xhujoy for explain this to me. I have another question, is it ok if we change the number of epoch and is it will affect the result of the outcome?

**Comment by xhujoy** [comment]
I just set the number of epoch according to the paper and don't test to change it during training.

**Comment by niccanicci** [comment]
Thank you @xhujoy very fast and good feedback

**Comment by Deeplearning20** [comment]
@xhujoy @niccanicci Hello，I have the same problem，,I run the code, and it turns out to be ’load failed.’Can this problem be ignored?
![image](https://user-images.githubusercontent.com/39185624/40882304-4551f486-6710-11e8-9a92-5cef564bc1c6.png)
