### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by syazw** [xhujoy/CycleGAN-tensorflow#17]
![screenshot from 2017-10-20 15-26-37](https://user-images.githubusercontent.com/32951997/31809629-29c88f0c-b5ab-11e7-84da-45ea8fa0d762.png)

Hye @xhujoy , how can i resolve this problem?

**Comment by xhujoy** [comment]
OOM maybe means out of memory. I don't have any idea about this problem.

**Comment by syazw** [comment]
![screenshot from 2017-10-23 22-36-20](https://user-images.githubusercontent.com/32951997/31895146-f4b3dd72-b842-11e7-92b6-b602e5b85943.png)

@xhujoy , 
how can i change batch_idxs from 1067 to minimum number?

**Comment by xhujoy** [comment]
If you want, you can change `arg.train_size` or directly change batch_idxs to any number less than 1067. See https://github.com/xhujoy/CycleGAN-tensorflow/blob/master/model.py#L146.
