### ISSUE TITLE
won't generate results

### ISSUE THREAD

**Issue by ybclaire** [xhujoy/CycleGAN-tensorflow#23]
In the Train model stage, using
python main.py --dataset_dir=/horse2zebra

Will generate no result:
/sample, /checkpoints /tests will be created but contains 0 files. 
In run Window
...
discriminatorA/d_bn2/offset:0
discriminatorA/d_h3_conv/Conv/weights:0
discriminatorA/d_bn3/scale:0
discriminatorA/d_bn3/offset:0
discriminatorA/d_h3_pred/Conv/weights:0
...

Did I miss anything?

**Comment by meggiezhou** [comment]
face the same question , have you solve it?
