### ISSUE TITLE
when training G

### ISSUE THREAD

**Issue by ray0809** [XHUJOY/CycleGAN-tensorflow#3]
Hi,when I was reading model.py,I found training Generator without freeze the Discriminator
Does it mean they are trained together?

**Comment by XHUJOY** [comment]
No. The operator of training G network is only built on the vars of G network.
`        self.da_optim = tf.train.AdamOptimizer(args.lr, beta1=args.beta1) \
                        .minimize(self.da_loss, var_list=self.da_vars)
        self.db_optim = tf.train.AdamOptimizer(args.lr, beta1=args.beta1) \
                        .minimize(self.db_loss, var_list=self.db_vars)
        self.g_a2b_optim = tf.train.AdamOptimizer(args.lr, beta1=args.beta1) \
                        .minimize(self.g_loss_a2b, var_list=self.g_vars_a2b)
        self.g_b2a_optim = tf.train.AdamOptimizer(args.lr, beta1=args.beta1) \
                        .minimize(self.g_loss_b2a, var_list=self.g_vars_b2a)`
