### ISSUE TITLE
Why the effect is not as good as the paper

### ISSUE THREAD

**Issue by Deeplearning20** [XHUJOY/CycleGAN-tensorflow#39]
![image](https://user-images.githubusercontent.com/39185624/41277110-cfb776ba-6e58-11e8-9bce-682eac7de9ec.png)
![image](https://user-images.githubusercontent.com/39185624/41277146-e78e510a-6e58-11e8-8072-e8fdba563428.png)
My epoch is 200, ‘--continue train，default=False’，The data set is also the author's.Why is the effect so bad and where is the problem? thank you all?

**Comment by paviddavid** [comment]
@Deeplearning20 Have you solved this issue?
