### ISSUE TITLE
Possibility of adding other pretrained models to the README (rather than just horse2zebra)

### ISSUE THREAD

**Issue by cschar** [XHUJOY/CycleGAN-tensorflow#42]
Hi,
Thanks for contributing with this amazing tensorflow implementation.

I trained the horse2zebra model on my home GPU (980Ti) but after a day I decided to use the pretrained model instead given by the URL. Wow was it so much more accurate! 

Would it be possible to add other pre-trained models to the project? Hosting them on a static drive somewhere? e.g. photo2monet/cezanne/ukiyoe etc...

I was looking at https://github.com/junyanz/CycleGAN and many[ pretrained models are provided](https://github.com/junyanz/CycleGAN#apply-a-pre-trained-model) but unfortunately I cannot find a suitable pytorch --> tensorflow model converter.

Thanks,

**Comment by chandakQ** [comment]
Could you please add the pre-trained model on apple2orange
