### ISSUE TITLE
identity mapping loss

### ISSUE THREAD

**Issue by iariav** [XHUJOY/CycleGAN-tensorflow#6]
Hi,
thank you for sharing this implementation.
do you plan on adding support for the identity mapping loss as described in the original paper?
thanks

**Comment by XHUJOY** [comment]
I think you can add an identity mapping loss easily. Just add the loss after this two lines, https://github.com/XHUJOY/CycleGAN-tensorflow/blob/master/model.py#L60, https://github.com/XHUJOY/CycleGAN-tensorflow/blob/master/model.py#L63
Now I have to do another project and will complete the rest of the project after a few weeks later.
